server:
  port: 8083

spring:
  application:
    name: app-service  # micro service unique ID
  profiles:
    active: dev
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      uri: http://localhost:8888
      name: token, database-app
  spring:
    kafka:
      bootstrap-servers: "localhost:9092"
      consumer:
        group-id: "producerGroupId"


eureka:
  client:
    register-with-eureka: true # register to eureka server
    fetch-registry: true # Getting instances' information from eureka server
    service-url:
      defaultZone : http://127.0.0.1:8761/eureka #Eureka Server's address

