server:
  port: 8083

spring:
  application:
    name: app-service  # micro service unique ID

eureka:
  client:
    register-with-eureka: true # register to eureka server
    fetch-registry: true # Getting instances' information from eureka server
    service-url:
      defaultZone : http://127.0.0.1:8761/eureka #Eureka Server's address

