server:
  port: 8888

spring:
  profiles:
    active: prod
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DDonghyeo/spring-msa
          search-paths: yml/**
          default-label: main
