server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:///Users/kimdonghyun/Desktop/Dong_Hyun/projects/spring-msa/yml