server:
  port: 8000

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8081/eureka
spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8082/
          predicates:
            - Path=/user/**
        - id: app-service
          uri: http://localhost:8083/
          predicates:
            - Path=/app/**

